In [5]:
# Q1.Import data healthcare-dataset-stroke-data.csv as df.
import pandas as pd

df = pd.read_csv("healthcare-dataset-stroke-data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   object
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(2), int64(4), object(6)
memory usage: 479.2+ KB

In [4]:
# Q2. Set the “id” column as the index.
df.set_index('id',inplace=True)

NameError: name 'df' is not defined

In [8]:
# Q3. Print the first 5 rows of data.
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,£228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,£202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,£105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,£171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,£174.12,24.0,never smoked,1

In [9]:
#Q4. Print the last 5 rows of the data.
df.tail()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
5105,18234,Female,80.0,1,0,Yes,Private,Urban,£83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,£125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,£82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,£166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,£85.28,26.2,Unknown,0

In [10]:
#Q5. Print the 100th row from the data.
print(df.iloc[99])

id                           4639
gender                     Female
age                          69.0
hypertension                    0
heart_disease                   0
ever_married                  Yes
work_type                Govt_job
Residence_type              Urban
avg_glucose_level          £82.81
bmi                          28.0
smoking_status       never smoked
stroke                          1
Name: 99, dtype: object

In [11]:
#Q6. Print the 100th index value from the data.
val_at_100_index = df.iloc[99]
print(val_at_100_index)

id                           4639
gender                     Female
age                          69.0
hypertension                    0
heart_disease                   0
ever_married                  Yes
work_type                Govt_job
Residence_type              Urban
avg_glucose_level          £82.81
bmi                          28.0
smoking_status       never smoked
stroke                          1
Name: 99, dtype: object

In [12]:
#Q7. Print the max of each column.
print(df.max())

id                      72940
gender                  Other
age                      82.0
hypertension                1
heart_disease               1
ever_married              Yes
work_type            children
Residence_type          Urban
avg_glucose_level      £99.97
bmi                      97.6
smoking_status         smokes
stroke                      1
dtype: object

In [13]:
#Q8. How many distinct `work_type`  are present in the data?
dist_work_type = df['work_type'].nunique()
print(dist_work_type)

5

In [14]:
#Q9. Print the value counts of gender.
gender_cnt = df['gender'].value_counts()
print(gender_cnt)

gender
Female    2994
Male      2115
Other        1
Name: count, dtype: int64

In [16]:
#Q10. Print the average avg_glucose_level for each gender.
df['avg_glucose_level'] = df['avg_glucose_level'].astype(float)
gender_gp = df.groupby('gender')

avg_glu_level = gender_gp['avg_glucose_level'].mean()

print(avg_glu_level)

ValueError: could not convert string to float: '£228.69'

In [17]:
#Q11. Describe all the data.
df.describe()

,id,age,hypertension,heart_disease,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,97.600000,1.000000

In [34]:
#Q12. Print the **MINIMUM** bmi.
df['bmi'].min()

10.3

In [35]:
#Q13. Find the average age.
df['age'].mean()

43.226614481409

In [37]:
#Q14. Check the null values in the dataset.
chk_null = df.isnull().sum()
print(chk_null)

gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [38]:
#Q15. Get the details of the row where the age is minimum.

min_age_index = df['age'].idxmin()
print(min_age_index)

print(df.loc[min_age_index])

47350
gender                 Female
age                      0.08
hypertension                0
heart_disease               0
ever_married               No
work_type            children
Residence_type          Urban
avg_glucose_level     £139.67
bmi                      14.1
smoking_status        Unknown
stroke                      0
Name: 47350, dtype: object